current_dir := ${CURDIR}
TARGET := basys3
TOP := RCA
SOURCES := ${current_dir}/../*.sv

# Include your constraint file path(s) below. Use either an XDC file
# or a PCF+SDC pair. Don't use all three file types.
XDC := ${current_dir}/Basys-3-Master.xdc
#PCF := ${current_dir}/<name of your xdc file if applicable>
#SDC := ${current_dir}/<name of your sdc file if applicable>

#include <path to f4pga-examples root directory>/common/common.mk
include ${current_dir}/common.mk