name: Github actions cocotb testbench
run-name: ${{ github.actor }} is running a testbench
on: [push]
jobs:
  cambios:
    runs-on: ubuntu-latest
    
    outputs:
      mux: ${{ steps.filter.outputs.mux }}

    steps:
      - name: Checking out repository code
        uses: actions/checkout@v4
      - name: Checking for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            mux:
              - 'mux_4_1/**'
    

  prueba_jobs:
    needs: cambios
    if: ${{ needs.changes.outputs.mux == 'true' }}
    runs-on: ubuntu-latest
    steps: 
      - run: echo"Test was successful :)"



  Run-Cocotb-Testbench:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v4
      - name: Installing iverilog
        run: sudo apt-get install iverilog
      - name: Setting up Python 3.10
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
      - name: Installing dependencies
        run: pip install cocotb
      - run: cocotb-config --version
      - name: Checking last commit
        uses: dorny/paths-filter@v3
        with:
          filters: |
            mux:
              - 'mux_4_1/**'
            alu:
              - 'alu/**'
            swl:
              -'switches_leds/**'
            cla:
              -'sumadores/CLA/**'
            fa:
              -'sumadores/FA/**'
            rca:
              -'sumadores/RCA/**'
      - name: Running testbench
        if: steps.changes.outputs.mux == 'true'
        run: make
        working-directory: mux_4_1

      - if: steps.changes.outputs.alu == 'true'
        run: make
        working-directory: alu

      - if: steps.changes.outputs.swl == 'true'
        run: make
        working-directory: switches_leds

      - if: steps.changes.outputs.cla == 'true'
        run: make
        working-directory: sumadores/CLA

      - if: steps.changes.outputs.fa == 'true'
        run: make
        working-directory: sumadores/FA

      - if: steps.changes.outputs.rca == 'true'
        run: make
        working-directory: sumadores/RCA

      - if: steps.changes.outputs.mux == 'false'
        run: echo"No changes detected in directory, skipping testbench execution."
