name: Prueba verificacion de archivos
run-name: ${{ github.actor }} is checking the files
on: [push]
jobs: 
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      mux: ${{ steps.filter.outputs.mux }}
      alu: ${{ steps.filter.outputs.alu }}
    steps:
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          mux:
            - 'mux_4_1/**'
          alu:
            - 'alu/**'

  mux:
    needs: changes
    if: ${{ needs.changes.outputs.mux == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v4
