name: Prueba verificacion de archivos
run-name: ${{ github.actor }} is checking the files
on: [push]
jobs: 
  changes:
    runs-on: ubuntu-latest
    outputs:
      mux: ${{ steps.filter.outputs.mux }}
      alu: ${{ steps.filter.outputs.alu }}
      display: ${{ steps.filter.outputs.display }}
      sw_led : ${{ steps.filter.outputs.sw_led }} 
    steps:
    - name: checking out repository code
      uses: actions/checkout@v4
    - name: checking for changes
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          mux:
            - 'mux_4_1/**/*.sv'
          alu:
            - 'alu/**'
          display:
            - 'display_7_segmentos/**'
          sw_led:
            - 'switches_leds/**'

  mux:
    needs: changes
    if: ${{ needs.changes.outputs.mux == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mux_4_1
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v4
      - name: Installing iverilog
        run: sudo apt-get install iverilog
      - name: Setting up Python 3.10
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
      - name: Installing dependencies
        run: pip install cocotb
      - run: cocotb-config --version
      - run: make

  alu:
    needs: changes
    if: ${{ needs.changes.outputs.alu == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./alu
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v4
      - name: Installing iverilog
        run: sudo apt-get install iverilog
      - name: Setting up Python 3.10
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
      - name: Installing dependencies
        run: pip install cocotb
      - run: cocotb-config --version
      - run: make
      - run: ls

  display:
    needs: changes
    if: ${{ needs.changes.outputs.display == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./display_7_segmentos
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v4
      - name: Installing iverilog
        run: sudo apt-get install iverilog
      - name: Setting up Python 3.10
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
      - name: Installing dependencies
        run: pip install cocotb
      - run: cocotb-config --version
      - run: make
      - run: ls

  sw_led:
    needs: changes
    if: ${{ needs.changes.outputs.sw_led == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./switches_leds
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v4
      - name: Installing iverilog
        run: sudo apt-get install iverilog
      - name: Setting up Python 3.10
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
      - name: Installing dependencies
        run: pip install cocotb
      - run: cocotb-config --version
      - run: make
